n1=float(input("Enter the first number "))
n2=float(input("Enter the second number "))
n3=float(input("Enter the third number "))
result=((n1+n2+n3)/3)
print("The average of n1,n2 and n3 is",result)